#!/bin/sh

echo "\033[1;33mBuilding for Windows ...\033[0m"
GOOS=windows go build -o bin/windows/bot.exe cmd/alvisd/main.go

echo "\033[1;33mBuilding for Darwin ...\033[0m"
GOOS=darwin go build -o bin/macos/bot cmd/alvisd/main.go

echo "\033[1;33mBuilding for Linux ...\033[0m"
env GOOS=linux GOARCH=386 CGO_ENABLED=0 go build -o bin/linux/bot cmd/alvisd/main.go
